name: Job Ad Scraper

on:
  schedule:
    - cron: '51 20 * * *'  # Runs at 2051 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pdfminer.six

    - name: Run scraper for permanent academic positions
      run: |
        python job_scraper.py \
          https://www.uni-potsdam.de/de/verwaltung/dezernat3/stellenausschreibungen/unbefristete-stellen-fuer-akademisches-personal \
          job_ads.db

    - name: Run scraper for administrative jobs / librarians
      run: |
        python job_scraper.py \
          https://www.uni-potsdam.de/de/verwaltung/dezernat3/stellenausschreibungen/verwaltung-und-bibliotheksdienst \
          job_ads.db

    - name: Run scraper for IT jobs
      run: |
        python job_scraper.py \
          https://www.uni-potsdam.de/de/verwaltung/dezernat3/stellenausschreibungen/it-und-technik \
          job_ads.db

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add job_ads.db
        git commit -m "Update job ads database" -a || echo "No changes to commit"
        git push
